CREATE OR REPLACE DATABASE RETAILDW_P6;

USE DATABASE RETAILDW_P6;

CREATE OR REPLACE SCHEMA RETAIL_SCHEMA;

USE SCHEMA RETAIL_SCHEMA;

CREATE FILE FORMAT IF NOT EXISTS retail_csv_format
    TYPE = 'csv'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('null', 'NULL');

SHOW FILE FORMATS;

CREATE OR REPLACE TABLE DIM_REGION (
    REGION_ID NUMBER PRIMARY KEY,
    REGION_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_STATE (
    STATE_ID NUMBER PRIMARY KEY,
    STATE_NAME VARCHAR(100),
    REGION_ID NUMBER,
    FOREIGN KEY (REGION_ID) REFERENCES DIM_REGION(REGION_ID)
);

CREATE OR REPLACE TABLE DIM_CITY (
    CITY_ID NUMBER PRIMARY KEY,
    CITY_NAME VARCHAR(100),
    STATE_ID NUMBER,
    FOREIGN KEY (STATE_ID) REFERENCES DIM_STATE(STATE_ID)
);

CREATE OR REPLACE TABLE DIM_CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_BRAND (
    BRAND_ID NUMBER PRIMARY KEY,
    BRAND_NAME VARCHAR(100),
    CATEGORY_ID NUMBER,
    FOREIGN KEY (CATEGORY_ID) REFERENCES DIM_CATEGORY(CATEGORY_ID)
);

CREATE OR REPLACE TABLE DIM_YEAR (
    YEAR_ID NUMBER PRIMARY KEY,
    YEAR_VALUE NUMBER
);

CREATE OR REPLACE TABLE DIM_QUARTER (
    QUARTER_ID NUMBER PRIMARY KEY,
    QUARTER_NAME VARCHAR(20),
    YEAR_ID NUMBER,
    FOREIGN KEY (YEAR_ID) REFERENCES DIM_YEAR(YEAR_ID)
);

CREATE OR REPLACE TABLE DIM_MONTH (
    MONTH_ID NUMBER PRIMARY KEY,
    MONTH_NAME VARCHAR(20),
    QUARTER_ID NUMBER,
    FOREIGN KEY (QUARTER_ID) REFERENCES DIM_QUARTER(QUARTER_ID)
);

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    CITY_ID NUMBER,
    MEMBERSHIP VARCHAR(50),
    FOREIGN KEY (CITY_ID) REFERENCES DIM_CITY(CITY_ID)
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    BRAND_ID NUMBER,
    PRICE NUMBER(12,2),
    FOREIGN KEY (BRAND_ID) REFERENCES DIM_BRAND(BRAND_ID)
);

CREATE OR REPLACE TABLE DIM_BRANCH (
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME VARCHAR(100),
    CITY_ID NUMBER,
    MANAGER_NAME VARCHAR(100),
    FOREIGN KEY (CITY_ID) REFERENCES DIM_CITY(CITY_ID)
);

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID NUMBER PRIMARY KEY,
    DATE_VALUE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR(20),
    WEEK_NO NUMBER,
    MONTH_ID NUMBER,
    IS_WEEKEND VARCHAR(10),
    FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH(MONTH_ID)
);

CREATE OR REPLACE TABLE FACT_SALES (
    SALE_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(14,2),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES DIM_BRANCH(BRANCH_ID),
    FOREIGN KEY (DATE_ID) REFERENCES DIM_DATE(DATE_ID)
);


CREATE OR REPLACE TABLE STG_CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50)
);

CREATE OR REPLACE TABLE STG_PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE NUMBER(12,2)
);

CREATE OR REPLACE TABLE STG_BRANCHES (
    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(100),
    MANAGER_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE STG_CALENDAR (
    DATE_ID NUMBER,
    DATE_VALUE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR(20),
    WEEK_NO NUMBER,
    MONTH VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR NUMBER,
    IS_WEEKEND VARCHAR(10)
);

CREATE OR REPLACE TABLE STG_SALES (
    SALE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(14,2)
);

COPY INTO STG_CUSTOMERS
FROM @RETAIL_STAGE/customersp6.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_CSV_FORMAT');

COPY INTO STG_PRODUCTS
FROM @RETAIL_STAGE/productsp6.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_CSV_FORMAT');

COPY INTO STG_BRANCHES
FROM @RETAIL_STAGE/branchesp6.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_CSV_FORMAT');

COPY INTO STG_CALENDAR
FROM @RETAIL_STAGE/calendarp6.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_CSV_FORMAT');

COPY INTO STG_SALES
FROM @RETAIL_STAGE/salesp6.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_CSV_FORMAT');

SELECT COUNT(*) FROM STG_CUSTOMERS;

SELECT COUNT(*) FROM STG_PRODUCTS;

SELECT COUNT(*) FROM STG_BRANCHES;

SELECT COUNT(*) FROM STG_CALENDAR;

SELECT COUNT(*) FROM STG_SALES;



USE DATABASE RETAILDW_P6;

USE SCHEMA RETAIL_SCHEMA;

LIST @RETAIL_STAGE;

INSERT INTO DIM_REGION (REGION_ID, REGION_NAME)
SELECT
    ROW_NUMBER() OVER (ORDER BY REGION_NAME),
    REGION_NAME
FROM (
    SELECT DISTINCT REGION_NAME
    FROM (
        SELECT REGION AS REGION_NAME
        FROM STG_BRANCHES

        UNION

        SELECT
            CASE
                WHEN STATE IN ('Telangana','Karnataka','Tamil Nadu','Andhra Pradesh','Kerala') THEN 'South'
                WHEN STATE IN ('Maharashtra','Gujarat') THEN 'West'
                WHEN STATE IN ('Delhi','Chandigarh','Rajasthan','Uttar Pradesh') THEN 'North'
                WHEN STATE IN ('West Bengal','Bihar') THEN 'East'
                WHEN STATE = 'Madhya Pradesh' THEN 'Central'
            END AS REGION_NAME
        FROM STG_CUSTOMERS
    )
    WHERE REGION_NAME IS NOT NULL
);

INSERT INTO DIM_STATE (STATE_ID, STATE_NAME, REGION_ID)
SELECT
    ROW_NUMBER() OVER (ORDER BY STATE_NAME),
    STATE_NAME,
    REGION_ID
FROM (
    SELECT DISTINCT
        X.STATE_NAME,
        R.REGION_ID
    FROM (
        SELECT
            STATE AS STATE_NAME,
            REGION AS REGION_NAME
        FROM STG_BRANCHES

        UNION

        SELECT
            STATE AS STATE_NAME,
            CASE
                WHEN STATE IN ('Telangana','Karnataka','Tamil Nadu','Andhra Pradesh','Kerala') THEN 'South'
                WHEN STATE IN ('Maharashtra','Gujarat') THEN 'West'
                WHEN STATE IN ('Delhi','Chandigarh','Rajasthan','Uttar Pradesh') THEN 'North'
                WHEN STATE IN ('West Bengal','Bihar') THEN 'East'
                WHEN STATE = 'Madhya Pradesh' THEN 'Central'
            END AS REGION_NAME
        FROM STG_CUSTOMERS
    ) X
    JOIN DIM_REGION R
        ON X.REGION_NAME = R.REGION_NAME
);

INSERT INTO DIM_CITY (CITY_ID, CITY_NAME, STATE_ID)
SELECT
    ROW_NUMBER() OVER (ORDER BY CITY_NAME, STATE_NAME),
    CITY_NAME,
    STATE_ID
FROM (
    SELECT DISTINCT
        X.CITY_NAME,
        X.STATE_NAME,
        S.STATE_ID
    FROM (
        SELECT CITY AS CITY_NAME, STATE AS STATE_NAME
        FROM STG_CUSTOMERS

        UNION

        SELECT CITY AS CITY_NAME, STATE AS STATE_NAME
        FROM STG_BRANCHES
    ) X
    JOIN DIM_STATE S
        ON X.STATE_NAME = S.STATE_NAME
);

INSERT INTO DIM_CATEGORY (CATEGORY_ID, CATEGORY_NAME)
SELECT
    ROW_NUMBER() OVER (ORDER BY CATEGORY_NAME),
    CATEGORY_NAME
FROM (
    SELECT DISTINCT CATEGORY AS CATEGORY_NAME
    FROM STG_PRODUCTS
);

INSERT INTO DIM_BRAND (BRAND_ID, BRAND_NAME, CATEGORY_ID)
SELECT
    ROW_NUMBER() OVER (ORDER BY BRAND_NAME, CATEGORY_ID),
    BRAND_NAME,
    CATEGORY_ID
FROM (
    SELECT DISTINCT
        P.BRAND AS BRAND_NAME,
        C.CATEGORY_ID
    FROM STG_PRODUCTS P
    JOIN DIM_CATEGORY C
        ON P.CATEGORY = C.CATEGORY_NAME
);

INSERT INTO DIM_YEAR (YEAR_ID, YEAR_VALUE)
SELECT
    ROW_NUMBER() OVER (ORDER BY YEAR_VALUE),
    YEAR_VALUE
FROM (
    SELECT DISTINCT YEAR AS YEAR_VALUE
    FROM STG_CALENDAR
);

INSERT INTO DIM_QUARTER (QUARTER_ID, QUARTER_NAME, YEAR_ID)
SELECT
    ROW_NUMBER() OVER (ORDER BY YEAR_VALUE, QUARTER_NAME),
    QUARTER_NAME,
    YEAR_ID
FROM (
    SELECT DISTINCT
        C.QUARTER AS QUARTER_NAME,
        C.YEAR AS YEAR_VALUE,
        Y.YEAR_ID
    FROM STG_CALENDAR C
    JOIN DIM_YEAR Y
        ON C.YEAR = Y.YEAR_VALUE
);

INSERT INTO DIM_MONTH (MONTH_ID, MONTH_NAME, QUARTER_ID)
SELECT
    ROW_NUMBER() OVER (ORDER BY YEAR_VALUE, QUARTER_NAME, MONTH_NAME),
    MONTH_NAME,
    QUARTER_ID
FROM (
    SELECT DISTINCT
        C.MONTH AS MONTH_NAME,
        C.QUARTER AS QUARTER_NAME,
        C.YEAR AS YEAR_VALUE,
        Q.QUARTER_ID
    FROM STG_CALENDAR C
    JOIN DIM_YEAR Y
        ON C.YEAR = Y.YEAR_VALUE
    JOIN DIM_QUARTER Q
        ON C.QUARTER = Q.QUARTER_NAME
        AND Q.YEAR_ID = Y.YEAR_ID
);

SELECT * FROM DIM_REGION;
SELECT * FROM DIM_STATE;
SELECT * FROM DIM_CITY;
SELECT * FROM DIM_CATEGORY;
SELECT * FROM DIM_BRAND;
SELECT * FROM DIM_YEAR;
SELECT * FROM DIM_QUARTER;
SELECT * FROM DIM_MONTH;

INSERT INTO DIM_CUSTOMER (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY_ID,
    MEMBERSHIP
)
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    CI.CITY_ID,
    C.MEMBERSHIP
FROM STG_CUSTOMERS C
JOIN DIM_CITY CI
    ON C.CITY = CI.CITY_NAME
JOIN DIM_STATE S
    ON C.STATE = S.STATE_NAME
    AND CI.STATE_ID = S.STATE_ID;

INSERT INTO DIM_PRODUCT (
    PRODUCT_ID,
    PRODUCT_NAME,
    BRAND_ID,
    PRICE
)
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    B.BRAND_ID,
    P.PRICE
FROM STG_PRODUCTS P
JOIN DIM_CATEGORY C
    ON P.CATEGORY = C.CATEGORY_NAME
JOIN DIM_BRAND B
    ON P.BRAND = B.BRAND_NAME
    AND B.CATEGORY_ID = C.CATEGORY_ID;

INSERT INTO DIM_BRANCH (
    BRANCH_ID,
    BRANCH_NAME,
    CITY_ID,
    MANAGER_NAME
)
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    CI.CITY_ID,
    B.MANAGER_NAME
FROM STG_BRANCHES B
JOIN DIM_CITY CI
    ON B.CITY = CI.CITY_NAME
JOIN DIM_STATE S
    ON B.STATE = S.STATE_NAME
    AND CI.STATE_ID = S.STATE_ID;

INSERT INTO DIM_DATE (
    DATE_ID,
    DATE_VALUE,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH_ID,
    IS_WEEKEND
)
SELECT
    C.DATE_ID,
    C.DATE_VALUE,
    C.DAY,
    C.DAY_NAME,
    C.WEEK_NO,
    M.MONTH_ID,
    C.IS_WEEKEND
FROM STG_CALENDAR C
JOIN DIM_YEAR Y
    ON C.YEAR = Y.YEAR_VALUE
JOIN DIM_QUARTER Q
    ON C.QUARTER = Q.QUARTER_NAME
    AND Q.YEAR_ID = Y.YEAR_ID
JOIN DIM_MONTH M
    ON C.MONTH = M.MONTH_NAME
    AND M.QUARTER_ID = Q.QUARTER_ID;

INSERT INTO FACT_SALES (
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
FROM STG_SALES;

SELECT COUNT(*) AS CUSTOMER_COUNT FROM DIM_CUSTOMER;

SELECT COUNT(*) AS PRODUCT_COUNT FROM DIM_PRODUCT;

SELECT COUNT(*) AS BRANCH_COUNT FROM DIM_BRANCH;

SELECT COUNT(*) AS DATE_COUNT FROM DIM_DATE;

SELECT COUNT(*) AS SALES_COUNT FROM FACT_SALES;


SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
ORDER BY TOTAL_SALES DESC;

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    B.BRAND_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRAND B
    ON P.BRAND_ID = B.BRAND_ID
GROUP BY B.BRAND_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    C.CATEGORY_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRAND B
    ON P.BRAND_ID = B.BRAND_ID
JOIN DIM_CATEGORY C
    ON B.CATEGORY_ID = C.CATEGORY_ID
GROUP BY C.CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    CI.CITY_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
JOIN DIM_CITY CI
    ON B.CITY_ID = CI.CITY_ID
GROUP BY CI.CITY_NAME
ORDER BY TOTAL_SALES DESC;


SELECT
    S.STATE_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
JOIN DIM_CITY CI
    ON B.CITY_ID = CI.CITY_ID
JOIN DIM_STATE S
    ON CI.STATE_ID = S.STATE_ID
GROUP BY S.STATE_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    R.REGION_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
JOIN DIM_CITY CI
    ON B.CITY_ID = CI.CITY_ID
JOIN DIM_STATE S
    ON CI.STATE_ID = S.STATE_ID
JOIN DIM_REGION R
    ON S.REGION_ID = R.REGION_ID
GROUP BY R.REGION_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    Y.YEAR_VALUE,
    M.MONTH_NAME,
    SUM(F.TOTAL_AMOUNT) AS MONTHLY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
JOIN DIM_MONTH M
    ON D.MONTH_ID = M.MONTH_ID
JOIN DIM_QUARTER Q
    ON M.QUARTER_ID = Q.QUARTER_ID
JOIN DIM_YEAR Y
    ON Q.YEAR_ID = Y.YEAR_ID
GROUP BY Y.YEAR_VALUE, M.MONTH_NAME
ORDER BY Y.YEAR_VALUE, M.MONTH_NAME;

SELECT
    Y.YEAR_VALUE,
    Q.QUARTER_NAME,
    SUM(F.TOTAL_AMOUNT) AS QUARTERLY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
JOIN DIM_MONTH M
    ON D.MONTH_ID = M.MONTH_ID
JOIN DIM_QUARTER Q
    ON M.QUARTER_ID = Q.QUARTER_ID
JOIN DIM_YEAR Y
    ON Q.YEAR_ID = Y.YEAR_ID
GROUP BY Y.YEAR_VALUE, Q.QUARTER_NAME
ORDER BY Y.YEAR_VALUE, Q.QUARTER_NAME;


SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.BRANCH_ID, B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT
    C.CUSTOMER_NAME,
    D.DATE_VALUE,
    SUM(F.TOTAL_AMOUNT) AS DAILY_PURCHASE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY C.CUSTOMER_NAME, D.DATE_VALUE
ORDER BY C.CUSTOMER_NAME, D.DATE_VALUE;

SELECT
    P.PRODUCT_NAME,
    B.BRAND_NAME,
    C.CATEGORY_NAME,
    SUM(F.QUANTITY) AS UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRAND B
    ON P.BRAND_ID = B.BRAND_ID
JOIN DIM_CATEGORY C
    ON B.CATEGORY_ID = C.CATEGORY_ID
GROUP BY P.PRODUCT_NAME, B.BRAND_NAME, C.CATEGORY_NAME
ORDER BY REVENUE DESC;

SELECT
    R.REGION_NAME,
    S.STATE_NAME,
    C.CITY_NAME,
    SUM(F.QUANTITY) AS UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
JOIN DIM_CITY C
    ON B.CITY_ID = C.CITY_ID
JOIN DIM_STATE S
    ON C.STATE_ID = S.STATE_ID
JOIN DIM_REGION R
    ON S.REGION_ID = R.REGION_ID
GROUP BY R.REGION_NAME, S.STATE_NAME, C.CITY_NAME
ORDER BY R.REGION_NAME, TOTAL_SALES DESC;

SHOW TABLES IN SCHEMA RETAILDW_P6.RETAIL_SCHEMA;









